# .github/workflows/nextjs-ci.yml
name: Next.js CI #  Give your workflow a descriptive name.

on:
  push:
    branches: [ 'main' ]  #  Trigger the workflow on pushes to the 'main' branch.
  pull_request:
    branches: [ 'main' ]  #  Trigger the workflow on pull requests targeting the 'main' branch.
  workflow_dispatch:  #  Allow manual trigger of the workflow.

jobs:
  build-and-lint:  #  Define a job named 'build-and-lint'.
    runs-on: ubuntu-latest  #  Specify the operating system for the job.

    steps:
      - name: Checkout code  #  Step to check out your repository's code.
        uses: actions/checkout@v3

      - name: Setup pnpm  #  Step to set up pnpm package manager.
        uses: pnpm/action-setup@v4
        with:
          version: 10  #  Use pnpm version 10 to match local version

      - name: Setup Node.js  #  Step to set up the Node.js environment.
        uses: actions/setup-node@v3
        with:
          node-version: '20'  #  Specify the Node.js version.
          cache: 'pnpm'  #  Enable pnpm dependency caching.

      - name: Install dependencies  #  Step to install project dependencies.
        run: pnpm install --frozen-lockfile

      - name: Run lint check  #  Step to run the lint check.
        run: pnpm run lint

      - name: Build application  #  Step to build the Next.js application.
        run: pnpm run build
        env:
          CI: true  #  Set the CI environment variable for strict mode checks.

      # Optional: Cache pnpm store for faster future builds.
      # - name: Cache pnpm store
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-